Post UI (and the List container as well)
ConnectOut-sdp/sdp2023 pull request #120
Opened 2023-05-10 20:15 UTC by DavidKalajdzic

Designed a xml layout for a Post #119 
This layout is designed to showcase all the essential information of a post, including the title, description, and number of likes. But that's not all - we've also added a horizontal scroll feature to display all the pictures in the post, giving users a seamless browsing experience. To make it even better, I've added a user profile section at the top, featuring the creator's profile picture. Clicking on it will take you directly to their profile page. With this new layout, users can easily explore and engage with posts, all while enjoying a sleek and visually appealing design.

It can be displayed in a ListView. I created the fragment that displays the list of Post, but not the view model (currently displaying a hard coded list) because this part will be another teammate's task.

2023-05-10 21:40 UTC, DavidKalajdzic commented on app/src/main/java/com/sdpteam/connectout/post/model/Post.java
> +    public Post(String id, String profileId, String eventId, String commentsChatId, List<String> imagesUrls, int nbrLikes, PostVisibility visibility, String title, String description) {
wrong

2023-05-11 20:30 UTC, EricSaikali requested changes
Good job with the UI and the draft of the List !
Please update me on the missing feature and suggestion that I had.
Nice work

2023-05-11 20:30 UTC, EricSaikali commented on app/src/main/java/com/sdpteam/connectout/post/view/PostsAdapter.java
> +                profileImageBtn.setScaleType(ImageView.ScaleType.CENTER_CROP);
I would suggest adding a TODO here, so that upon doing the viewModel class, the encapsulation of the MVVM is restored

2023-05-11 20:32 UTC, DavidKalajdzic commented on app/src/main/res/layout/activity_posts.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
Yes, good catch

2023-05-11 21:24 UTC, DavidKalajdzic commented on app/src/main/res/layout/post_list_item_view.xml
> +            android:id="@+id/post_profile_bar"
Yes I will add a indicator as well as a toast when we click on it so users can understand what the icon means.

I forgot to add the button to open the Event (if the evenId is not null ofc)

2023-05-11 21:57 UTC, EricSaikali approved these changes
Nice work !

2023-05-11 22:17 UTC, merged